services:
  postgres:
    image: postgres:16
    container_name: todo-list-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_list_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: